apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: mee3i3bw1-go 
  janus-idp.io/tekton: mee3i3bw1-go
  backstage.io/kubernetes-id: mee3i3bw1-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: mee3i3bw1-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml